# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 03:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxMsgHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('msg_cate', models.CharField(blank=True, choices=[('recv', 'recv'), ('send', 'send')], help_text='消息种类，接收 or 发送', max_length=10, null=True)),
                ('msg_type', models.CharField(help_text='消息类型，文本/语音...', max_length=50)),
                ('from_user', models.CharField(blank=True, max_length=100, null=True)),
                ('to_user', models.CharField(blank=True, max_length=100, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('file_path', models.FilePathField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='WxMsgRecvHistory',
        ),
        migrations.DeleteModel(
            name='WxMsgSendHistory',
        ),
        migrations.AddField(
            model_name='wxraw',
            name='http_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
