# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0002_auto_20170827_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxmsghistory',
            name='uin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wxraw',
            name='uin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
