# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0003_auto_20170827_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uin', models.CharField(blank=True, max_length=128, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=128, null=True)),
                ('head_img_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('remark_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('signature', models.TextField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('login_total', models.IntegerField(blank=True, help_text='累计登录次数', null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='wxmsghistory',
            name='from_group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wxmsghistory',
            name='from_user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wxmsghistory',
            name='to_group_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wxmsghistory',
            name='to_user_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
