# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0004_auto_20170827_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uin', models.CharField(blank=True, max_length=128, null=True)),
                ('login_on', models.DateTimeField(blank=True, null=True)),
                ('sid', models.CharField(blank=True, max_length=128, null=True)),
                ('skey', models.CharField(blank=True, max_length=128, null=True)),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('synckey', models.CharField(blank=True, max_length=128, null=True)),
                ('pass_ticket', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='login_total',
            field=models.IntegerField(default=0, help_text='累计登录次数'),
        ),
    ]
