# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0005_auto_20170827_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxloginhistory',
            name='cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
