# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0006_wxloginhistory_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxloginhistory',
            name='qr_image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
