# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxr', '0007_wxloginhistory_qr_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxloginhistory',
            name='pid',
            field=models.IntegerField(blank=True, help_text='监听的进程ID', null=True),
        ),
    ]
